### ISSUE TITLE
VSCodeやcoc.nvimのYarn PnP対応を忘れている

### ISSUE THREAD

**Issue by YukiYuigishi** [KurumeNCT-Robocon/minkberry#6]
VSCodeやcoc.nvim等で開発を行おうとすると、問題がないはずの場所でts2307(Cannnot find module)が発生する

**Comment by mirror-kt** [comment]
Yarn v3のPnPを使ってるからですね
対応します

**Comment by mirror-kt** [comment]
FYI: https://yarnpkg.com/getting-started/editor-sdks

VSCode、neovimともにzipファイルを開ける拡張機能が必要です
